Articulos/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
   path('', home),
   path('entrada/', entrada, name='entrada'),
   path('login/', login_request, name='login'),
   path('logout/', LogoutView.as_view(template_name = "logout.html"), name='logout'),
   path('registrate/', registrate, name='registrate'),
   path('agregarAvatar/', agregarAvatar, name= 'agregarAvatar'),
   path('editarPerfil/', editarPerfil, name= 'editarPerfil'),
   path('articulo/', Articulos, name= 'articulo'),  
   path('inicio/', home ,name='inicio'),
   path('detalle/<id_entrada>', detalleEntrada, name='detalle'),
   path('editar/<id_entrada>', editarEntrada, name='editarEntrada'),
   path('entradas/', entradas, name='entradas'),
   path('nosotros/', Nosotros ,name='nosotros'),
   path('borrar/<id_entrada>', borrarEntrada, name='borrar'),
   path('comentar/<id_entrada>', comentarEntrada, name='comentar'),

]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Articulos.urls')),
    path('', include('Mensajes.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Articulos/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField




class Entrada(models.Model):
    titulo = models.CharField(max_length=80)
    subtitulo = models.CharField(max_length=80)
    contenido = RichTextField(blank=True, null=True)
    fecha_ingreso = models.DateField(auto_now_add=True)
    imagen = models.ImageField(upload_to='entrada', null=True, blank=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

class Avatar(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    imagen= models.ImageField(upload_to='avatares', null=True, blank=True)

class Comentario(models.Model):
    nombre = models.CharField(max_length=50)
    comentario = models.TextField(max_length=400)


class Comentarios(models.Model):
    entrada_id = models.IntegerField()
    nombre = models.CharField(max_length=50)
    comentario = models.TextField(max_length=400)

    def __str__(self):
        return self.nombre

Articulos/forms.py
from django import forms
from .models import Entrada
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from ckeditor.widgets import CKEditorWidget




class EntradaForm(forms.Form):
    titulo = forms.CharField(max_length=80, widget=forms.TextInput)
    subtitulo = forms.CharField(max_length=80, required=False)
    contenido = forms.CharField(widget=CKEditorWidget())
    imagen = forms.ImageField(required=False)
    

        

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label="Usuario")
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class AvatarForm(forms.Form):
    imagen= forms.ImageField(label="Imagen")


class UserEditForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput)

    first_name= forms.CharField(max_length=50)
    last_name= forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']
        help_texts = {k:"" for k in fields}


class ComentarioForm(forms.Form):
    nombre = forms.CharField(label='Nombre :', max_length=50)
    comentario = forms.CharField(widget=forms.Textarea)


class ComEntradaForm(forms.Form):
    nombre = forms.CharField(label='Autor :', max_length=50)
    comentario = forms.CharField(widget=forms.Textarea)

Articulos/views.py
from ast import Delete
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from Mensajes.models import Mensajes




def home(request):  #comentariosForms
    articulos = Entrada.objects.all().order_by('-id')[:3]
    nuevos = Mensajes.objects.filter(leido=False, nombre=request.user).count()
    if request.method == "POST":
        form = ComentarioForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            comentario = form.cleaned_data['comentario']
            obj = Comentario(nombre=nombre, comentario=comentario)
            obj.save()
            #Configurar Correo
            #asunto = form.cleaned_data['nombre']
            #mensaje = form.cleaned_data['comentario']
            #direccion = "entregafinal2022@yahoo.com"
            #destinatario = ["pameyari2529@gmail.com"]

            #send_mail(asunto,mensaje,direccion,destinatario)

            form = ComentarioForm()
            mensaje = "Gracias por tu comentario"
            return render(request,"bienvenida.html", {"articulos":articulos, "nuevos": nuevos, "mensaje":mensaje,"form":form})
    form = ComentarioForm()
    return render(request, "bienvenida.html", {"articulos":articulos, "nuevos":nuevos, "form":form})

@login_required
def entrada(request):
    if request.method == "POST":

        form = EntradaForm(request.POST, request.FILES)
        if form.is_valid():
            
            info= form.cleaned_data
            titulo = info["titulo"]
            subtitulo = info["subtitulo"]
            contenido = info["contenido"]
            imagen= info["imagen"]
            entrada = Entrada(titulo=titulo, subtitulo=subtitulo, contenido=contenido, autor=request.user, imagen=imagen)
            entrada.save()
            articulos = Entrada.objects.all().order_by('-id')[:3]
            #last_ten_in_ascending_order = reversed(last_ten)()
            return render(request, "bienvenida.html", {"articulos": articulos})
    else:
        form = EntradaForm()

    return render(request, "entradaForm.html", {"form":form})


def login_request(request):
    
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usu = request.POST['username']
            clave = request.POST['password']
            usuario = authenticate(username = usu, password = clave)
            if usuario is not None:
                login(request, usuario)
                articulos = Entrada.objects.all().order_by('-id')[:3]
                nuevos = Mensajes.objects.filter(leido=False, nombre=request.user).count()
                return render(request, 'bienvenida.html', {'articulos':articulos, 'nuevos': nuevos, 'mensaje':f"Bienvenido {usuario}"})
            else:
                return render(request, 'loginForm.html', {'form':form, 'mensaje': 'Usuario o clave incorrecta'})
        else:
            return render(request, 'loginForm.html', {'form':form, 'mensaje':f"FORMULARIO INVALIDO"})
    else:
        form = AuthenticationForm()
    return render(request, 'loginForm.html', {'form':form})

def registrate(request):
    if request.method == "POST":

        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]  # es igual a form.cleaned_data.get('username')
            form.save()
            # u = User.objects.get(username=username)
            # permission = Permission.objects.get(codename='view_personal')
            # u.user_permissions.add(permission)
            return render(request, "registro.html", {"mensaje":f"Usuario creado: { username }"})
    else:
        form = UserRegisterForm()

    return render(request, "registroForm.html", {"form":form})


@login_required
def agregarAvatar(request):
    if request.method == 'POST':
        formulario=AvatarForm(request.POST, request.FILES)
        if formulario.is_valid():
            try:
                avatarViejo=Avatar.objects.get(user=request.user)
                if(avatarViejo.imagen):
                    avatarViejo.delete()
            except:
                pass
            avatar=Avatar(user=request.user, imagen=formulario.cleaned_data['imagen'])
            avatar.save()
            return render(request, 'bienvenida.html', {'usuario':request.user, 'mensaje':'AVATAR AGREGADO EXITOSAMENTE'})
    else:
        formulario=AvatarForm()
    return render(request, 'agregarAvatar.html', {'formulario':formulario, 'usuario':request.user})


@login_required
def editarPerfil(request):
    usuario=request.user

    if request.method == 'POST':
        formulario=UserEditForm(request.POST, instance=usuario)
        if formulario.is_valid():
            informacion=formulario.cleaned_data
            usuario.email=informacion['email']
            usuario.password1=informacion['password1']
            usuario.password2=informacion['password2']
            usuario.save()

            return render(request, "bienvenida.html", {'usuario':usuario, 'mensaje':'PERFIL EDITADO EXITOSAMENTE'})
    else:
        formulario=UserEditForm(instance=usuario)
    return render(request, 'editarPerfil.html', {'formulario':formulario, 'usuario':usuario.username})


def Articulos(request):
    comentar=Comentarios.objects.all()
    return render(request,"entradas.html",{"comentar":comentar})

    
def inicio(request):
    return render(request,"bienvenida.html")


def detalleEntrada(request, id_entrada):
    try:
        entrada = Entrada.objects.get(id=id_entrada)
        comentarios = Comentarios.objects.filter(entrada_id=id_entrada)
    except:
        return render(request,"detalleEntrada.html",{"mensaje":'La entrada no existe'})
    return render(request,"detalleEntrada.html",{"entrada":entrada, "comentarios": comentarios})

def entradas(request):
    articulos = Entrada.objects.all().order_by('-fecha_ingreso')
    return render(request, "entradas.html", {"entradas":articulos})

@login_required
def editarEntrada(request, id_entrada):
    try:
        entrada = Entrada.objects.get(id=id_entrada)
    except:
        return render(request, "bienvenida.html", {'mensaje':'El articulo no existe'})
    if entrada.autor != request.user:
        return render(request, "bienvenida.html", {'mensaje':'Uds no es el autor del articulo'})

    if request.method == "POST":
        form = EntradaForm(request.POST, request.FILES)
        if form.is_valid():
            info = form.cleaned_data
            entrada.titulo = info["titulo"]
            entrada.subtitulo = info["subtitulo"]
            entrada.contenido = info["contenido"]
            entrada.autor=request.user
            if info["imagen"] != None:
                entrada.imagen = info["imagen"]
            entrada.save()
            return redirect('inicio')
    else:
        form = EntradaForm(initial={"titulo":entrada.titulo, "subtitulo":entrada.subtitulo,
                                    "contenido":entrada.contenido, "autor":request.user, "imagen":entrada.imagen})

    return render(request, "editarEntrada.html", {"form":form, "id_entrada":entrada.id})

def Nosotros(request):
    return render(request,"nosotros.html")


@login_required
def borrarEntrada(request, id_entrada):
    try:
        entrada = Entrada.objects.get(id=id_entrada)
    except:
        return render(request,"bienvenida.html",{"mensaje":'La entrada no existe'})

    entrada.delete()
    return redirect('inicio')
    

def comentarEntrada(request, id_entrada):
    
    if request.method == "POST":
        form = ComEntradaForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data['nombre']
            comentario = form.cleaned_data['comentario']
            obj = Comentarios(entrada_id = id_entrada, nombre=nombre, comentario=comentario)
            obj.save()
            entrada = Entrada.objects.get(id=id_entrada)
            comentarios = Comentarios.objects.filter(entrada_id=id_entrada)
            return render(request,"detalleEntrada.html", {"entrada": entrada, "comentarios": comentarios})
    form = ComEntradaForm()
    return render(request, "comEntrada.html", { "id_entrada": id_entrada, "form":form})

Articulos/templates/bienvenida.html
{% extends "padre.html" %}
{% load static %} 

{% block titulo %} 
<h1 class="mb-5">Bienvenidos</h1>
{% endblock %} 


{% block contenido %} 
<section>
    <form action="" method="post" style="margin: auto; width: 560px;">
        {% csrf_token %}
        <h2>Comunicate con nosotros</h2>
        {{ form.as_p }}
        <a href=""  type="submit" class="blogs-button" style="width: 50vw; margin-left : 10vw;">Enviar Comentario</a>
        <!--<input type="submit" name="enviar" value="Enviar Comentario" >-->
        {% if mensaje %}
        <h2>{{ mensaje }}</h2>
        {% endif %}
    </form> 
</section>
{% endblock %} 

Articulos/templates/comEntrada.html
{% extends "padre.html" %}
{% load static %}

{% block Articulo %} 
    <div>
                
        {% if form.error %}
        <p style= "color:red">ERROR EN EL FORMULARIO</p>
        {% endif %}
    <section style="margin: 0 auto;margin-left:500px;margin-top: 20px;margin-bottom: 300px;">
        <form class="form-table" action="{% url 'comentar' id_entrada %}" method="POST" style="margin-top: 10px;"> {% csrf_token %}        
            <table>
                {{ form.as_table }}
            </table>
            <section style="margin-left:260px; margin-top: 10px;">
                <input type="submit" class ="btn btn-primary" value="Enviar" style="font-size:20px;border: 3px solid #47cfac">
            </section>
        </form>
    </section>
    </div>
{% endblock %}

Articulos/templates/detalleEntrada.html
{% extends "padre.html" %}
{% load static %} 

{% block Articulo %}
  <section class="grid-container blogpost-img-container">
    <img src="{% static '\imagenes\aaa.jpg' %}" alt="" />
  </section>
  <section class="blogpost-main-container">
    <div class="grid-container-blog">
       <h3 style="color:blue;font-size: 30px;">Noticias</h3>
    </div>
  </section>
  <section style="text-align: center;">
    {% if entrada %}
      <h3 style="color:blue;font-size:30px;"> Titulo:" {{ entrada.titulo }} "</h3>
      <p style="text-decoration: underline;font-size:20px;">Articulo:</p> 
      <p>{{ entrada.contenido|safe }}</p>
      {% if entrada.imagen %}
      <img src="{{ entrada.imagen.url }}" alt="Imagen de entrada" style="width:350px ;">
      {% endif %}
      <h4>Autor: {{ entrada.autor }}</h4>
      <p>Creado el: {{ entrada.fecha_ingreso }}</p>
      <br><br>
      {% if comentarios %}
      {% for comentario in comentarios %}
      <p> {{ comentario.nombre }}</p>
      <p>{{ comentario.comentario }}</p>
      {% endfor %}
      {% endif %}
      <br><br>
      {% if request.user == entrada.autor %}
      <a href="{% url 'editarEntrada' entrada.id %}">EDITAR</a>
      <a href="{% url 'borrar' entrada.id %}">BORRAR</a>
      {% endif %}
      <section style="border: 3px solid #47cfac;border-radius:10px;width:300px;height: 100px;margin-top: 10px;text-align: center;margin-left: 630PX;margin-bottom: 20PX;">
        <section style="margin-bottom: 35px;">
            <h1>Sector de Comentarios</h1>
          <a href="{% url 'comentar' entrada.id %}" class="blogs-button" >COMENTAR</a>
        </section>
      </section>
    {% endif %}
    {% if mensaje %}
    <p>{{ mensaje }}</p>
    {% endif %}
  </section>



{% endblock %}

Articulos/templates/editarEntrada.html
{% extends "padre.html" %}
{% load static %}

        {% block Articulo %} 
            <div>
                
                <form class="form-table" action="{% url 'editarEntrada' id_entrada %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                
                    <table>
                        {{ form.media }}
                        {{ form.as_table }}
                    </table>
            
                    <input type="submit" class="btn btn-sm btn-primary" value="Editar">
                    {% if mensaje %}
                        <h2>{{ mensaje }}</h2>
                    {% endif %}
                </form>
            </div>
        {% endblock %}
 

Articulos/templates/editarPerfil.html
<html>
    <head>
        <title>Login</title>
        {% load static %} 
        <link href="{% static '\styles.css' %}" rel="stylesheet" />
        <link href="{% static '\main.css' %}" rel="stylesheet" />
        <link href="{% static '\media-queries.css' %}" rel="stylesheet"  />
        <link href="{% static '\font\flaticon.css' %}" rel="stylesheet" />
    </head>
    <body style="background-color:white">
        <header>
    
            <section class="header-icons-container">
            </section>
              <nav>
                  <section class="nav-logo-container">
                      <h1 style="font-size: 30px;color: white;"><a href="{% url 'inicio' %}"style="font-size: 30px;color: white;">GAMUFI</a></h1>
                  </section>
            </nav>
          </header>
        {% block Articulo %} 
        <div class="main-boxs">
            <img src="{% static '\imagenes\user.png' %}" class="avatar" alt="avatar">
            <h1 style="color: #2c3e50;">Modificar Datos</h1>
            <form">
            <form class="form-table" action="{% url 'editarPerfil' %}" method="POST">
                {% csrf_token %}          
                <table style="color: #2c3e50;margin-top: -35px;">
                {{ formulario.as_table }}
                </table>       
                <input type="submit" class="btn btn-sm btn-primary" value="Confirmar" style="margin-top: -8px;"> 
                <a href="{% url 'agregarAvatar' %}"><input type="button" class="btn btn-sm btn-primary"  value="Agregar Avatar" style="margin-top: -8px;"></a> 
                <a href="{% url 'inicio' %}"><input type="button" class="btn btn-sm btn-primary"  value="Salir" style="margin-top: -8px;"></a> 
       
            </form>
        </div>
        {% endblock %}


    </body>

</html>

Articulos/templates/entradaForm.html
{% extends "padre.html" %}
{% load static %}

        {% block Articulo %} 
            <div>
                
                <form class="form-table" action="{% url 'entrada' %}" method="POST" enctype="multipart/form-data">
                    <section style="margin: o auto; text-align: center;">
                        {% csrf_token %}
                        <h1 style="color: blue;text-align: center;">Sector para Cargar los Articulos</h1>
                        <h3 style="text-align: center;">Ingrese los siguientes campos y precione "Cargar Articulos" para Finalizar</h3>
                        <table style="margin:0 auto; margin-top: 20px;">
                            {{ form.media }}
                            {{ form.as_table }}
                        </table>
                        <section style="text-align: center; margin-bottom: 15px;">
                        <input type="submit" class="btn btn-sm btn-primary" value="Ingresar" style="font-size:20px;border: 3px solid #47cfac">
                        </section>
                        {% if mensaje %}
                            <h2>{{ mensaje }}</h2>
                        {% endif %}
                    </section>
                </form>
            </div>
        {% endblock %}
 

Articulos/templates/inicio.html
{% block contenido %} 
<section>
    {% if usuario.is_authenticated %}
    <div class="user">
        <img style="width: 60px; height: 60px; border-radius: 50%;" src="{{ usuario.avatar_set.first.imagen.url }}" alt="imagen de perfil"/>
        <div id="hormenu">
            <ul>
                <li>
                    <p class="user">{{ usuario.username|title }}</p>
                    <ul>
                        <li><a href="#">Datos</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    {% endif %}
    
    {{ mensaje }}
</section>
{% endblock %} 

Articulos/templates/nosotros.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>
    <link href="{% static '\main.css' %}" rel="stylesheet" />
    <link href="{% static '\media-queries.css' %}" rel="stylesheet"  />
    <link href="{% static '\font\flaticon.css' %}" rel="stylesheet" />
    {% block estilos %}
    {% endblock %}
  </head>
  <body>
    <header>
    
      <section class="header-icons-container">
      </section>
        <nav>
            <section class="nav-logo-container">
                <h1 style="font-size: 30px;color: white;"><a href="{% url 'inicio' %}"style="font-size: 30px;color: white;">GAMUFI</a></h1>
            </section>
            <section class="profile-link">
              {% if not request.user.is_authenticated %}
                <i><a href="{% url 'login' %}" style="margin-left:auto; margin-right: auto;">Ingresar</a>
                <i><a href="{% url 'nosotros' %}"  style="margin-left:auto; margin-right: auto;">Acerca de Nosotros</a>
                <a href="{% url 'registrate' %}" style="margin-left:auto; margin-right: auto;">Registrate</a>
              {% endif %}
            </section>
      </nav>
    </header>
    {% block Articulo %}
    <main class="blogs-main">
        {{ mensaje }}
        {% if request.user.is_authenticated %}
        <div class="user">
            <img style="width: 60px; height: 60px; border-radius: 50%;" src="{{ request.user.avatar_set.first.imagen.url }}" alt="imagen de perfil"/>
            <div id="hormenu" style="color: white;">
                <ul>
                    <li>
                        <p class="user" style="color: white;">{{ request.user.username|title }}</p>
                        <ul>
                            <li><a href="{% url 'editarPerfil' %}">Editar Perfil</a></li>
                            <li><a href="">Sector de Mensajes</a></li>
                            <a href="{% url 'logout' %}" style="margin-left:auto; margin-right: auto;"> Salir</a>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        {% endif %}
      <section class="blogs-news-container">
        <div class="grid-container blogs-main-new">
            <h3 style="color:blue">Acerca de Nosotros</h3>
            <div class="blogs-news-img-container">
            <img src="{% static '\imagenes\coder.jpeg' %}" alt="" />
        </div>
    
        <div class="blogs-news-info-container">
            <h2>Bienvenidos a Nustro Blog de Articulos  Turisticos</h2>
            <p>
              Este Blog, esta creado para aquellas personas que necesitan brindar o recibir
              Informacion respecto a algunos lugares turisticos
            </p>
        </div>
      </section>
    <section class="blogs-post-container" style="text-align: center;position: 30px;">
            <h1>Integrantes</h1>
                <li>Fiorini Pablo</li>
                <li>Gareis Pablo</li>
                <li>Muzyka Pablo</li>
             <h2>Curso</h2>
            <li>Python</li>
            <h2>Comision</h2>
            <li>37360</li>
            <h2>Plataforma: Coder House</h2>
            <li><a href="https://www.coderhouse.com/">Link</a></li>
        </article>
      </section>
      
    </main>
{% endblock %}
    <footer>
      <p>Página Creada por los Alumnos de Coder House ---> Curso "Python"</p>
    </footer>

  </body>
</html>

Articulos/templates/padre.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'imagenes/favicon.png' %}" />
    <title>Blog</title>
    <link href="{% static '\main.css' %}" rel="stylesheet" />
    <link href="{% static '\media-queries.css' %}" rel="stylesheet"  />
    <link href="{% static '\font\flaticon.css' %}" rel="stylesheet" />
    {% block estilos %}
    {% endblock %}
  </head>
  <body>
    <header>
    
      <section class="header-icons-container">
      </section>
        <nav>
            <section class="nav-logo-container">
                <h1 style="font-size: 30px;color: white;"><a href="{% url 'inicio' %}"style="font-size: 30px;color: white;">GAMUFI</a></h1>
            </section>
            <section class="profile-link">
              {% if not request.user.is_authenticated %}
                <i><a href="{% url 'login' %}" style="margin-left:auto; margin-right: auto;">Ingresar</a>
                <a href="{% url 'registrate' %}" style="margin-left:auto; margin-right: auto;">Registrate</a>
              {% endif %}
              {% if request.user.is_authenticated %}
                <i><a href="{% url 'entrada' %}" style="margin-left:auto; margin-right: auto;">Nuevo Articulo</a>
              {% endif %}
                <i><a href="{% url 'nosotros' %}" style="margin-left:auto; margin-right: auto;">Acerca de Nosotros</a>
            </section>
      </nav>
    </header>
    {% block Articulo %}
    <main class="blogs-main">
        {{ mensaje }}
        {% if request.user.is_authenticated %}
        <div class="user">
            <img style="width: 60px; height: 60px; border-radius: 50%;" src="{{ request.user.avatar_set.first.imagen.url }}" alt="imagen de perfil"/>
            <h3>{{ request.user }}</h3>
            <div id="hormenu" style="color: white;">
                <ul>
                    <li>
                        <p class="user" style="color: white;">{{ request.user.username|title }}</p>
                        <ul>
                            <li><h4 style="color:blue;">Hay {{ nuevos }} nuevos mensajes</h4></li>
                            <li><a href="{% url 'editarPerfil' %}">Editar Perfil</a></li>
                            <li><a href="{% url 'mensajes' %}">Sector de Mensajes</a></li>
                            <li><a href="{% url 'logout' %}" style="margin-left:auto; margin-right: auto;"> Salir</a></li>
                        </ul>
                    </li>
                </ul>
              </div>
        </div>
        {% endif %}
      <section class="blogs-news-container">
        <div class="grid-container blogs-main-new">
            <h3 style="color:blue">Noticias</h3>
            <div class="blogs-news-img-container">
            <img src="{% static '\imagenes\fondo.jpg' %}" alt="" />
        </div>
    
        <div class="blogs-news-info-container">
            <h2>Experiencias de Emigraciones de Argentinos en este año</h2>
            <p>
              Estos Articulos que presentamos a continuación, 
              mencionan distintas experiencias contadas por Argentinos que están viviendo en distintas locaciones.
            </p>
        </div>
      </section>
    <section class="blogs-post-container">
        <div class="grid-container">
            <h3 class="blogs-post-titulo-post" style="color:blue;">Articulos Más Recientes</h3>
            {% for elemento in articulos %}
            <article class="post-container" style="text-align: center;">
                {% if elemento.imagen %}
                <img src="{{ elemento.imagen.url }}" alt="" style="border-radius:20%;">
                {% endif %}
                <h3>Título: {{ elemento.titulo }}</h3>
                <!-- <p>Contenido: {{ elemento.contenido|safe }}</p> -->
                <h4>Autor: {{ elemento.autor }}</h4> 
                <a href="{% url 'detalle' elemento.id %}"  class="blogs-button">Leer más</a>
            </article>
            {% endfor %}
            <section style="text-align: center;">
              <a href="{% url 'entradas' %}"  class="blogs-button">Ver todos los Articulos</a>
            </section >
            <section style="border: 3px solid #22272d;border-radius:20px;width:990px;height: 350px;margin-top: 25px;text-align: center;">
              {% block contenido %}

              {% endblock %}
            </section>
        </div>
      </section>
      
    </main>
{% endblock %}
    <footer>
      <p>Página Creada por los Alumnos de Coder House ---> Curso "Python"</p>
    </footer>

  </body>
</html>